const CreateGameConst = {
  CREATE_GAME_SUCCESS: "CREATE_GAME_SUCCESS",
  CREATE_GAME_IN_PROGRESS: " CREATE_GAME_IN_PROGRESS",
  CREATE_GAME_FAILED: "CREATE_GAME_FAILED"
};
export default CreateGameConst;
